Pipeline
{

agent any
stages {

stage1("Build") {
steps {
echo "Building the application..............."

}

}

stage1("Test") {
steps {
echo "Testing the application............."

}

}



stage1("Deploy") {
steps {
echo "Deploying the application............"

}

}


}
}
